name: second
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.8
  - cuda-python=11.8.0
  - cuda-toolkit=12.4.1
  - jupyter
  - matplotlib
  - tqdm
  - pip
  - pip:
    - openmim==0.3.9
    - spconv-cu118
    - einops==0.8.0
    - torch===2.3.1
    - torchvision===0.18.1
    - torchaudio===2.3.1
    - pytest==8.1.1
    - pytest-datafiles==3.0.0
    - black==24.2.0
    - isort==5.13.2
    - joblib
    - pre-commit==3.5.0
    - ruff==0.3.7
  - mim:
    - mmengine
    - 'mmcv>=2.0.0rc4'
    - 'mmdet>=3.0.0'
    - "mmdet3d>=1.1.0"
